# Generated by Django 4.1 on 2022-08-08 11:07

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesDicty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='KeyPermissionsDicty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masterKey', models.BooleanField()),
                ('hrKey', models.BooleanField()),
                ('vote', models.BooleanField()),
                ('propose', models.BooleanField()),
                ('sendDelegate', models.BooleanField()),
                ('receiveDelegate', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfileImageDicty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileImageHash', models.CharField(max_length=46)),
                ('profileImageUrl', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VaultDicty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaultName', models.CharField(max_length=50)),
                ('majority', models.DecimalField(decimal_places=2, max_digits=2)),
                ('daoMembers', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='VotingDicty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participationRate', models.DecimalField(decimal_places=2, max_digits=2)),
                ('votingMajority', models.DecimalField(decimal_places=2, max_digits=2)),
                ('minVotingDelay', models.DecimalField(decimal_places=0, max_digits=4)),
                ('minVotingPeriod', models.DecimalField(decimal_places=0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='PermissionsDicty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upAddress', models.CharField(max_length=42)),
                ('keyPermissions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.keypermissionsdicty')),
            ],
        ),
        migrations.CreateModel(
            name='Daos',
            fields=[
                ('daoName', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('time', models.CharField(max_length=10)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.categoriesdicty')),
                ('keyPermissions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.permissionsdicty')),
                ('profileImage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.profileimagedicty')),
                ('vaultDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.vaultdicty')),
                ('votingParameters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.votingdicty')),
            ],
        ),
    ]
