# Generated by Django 4.1 on 2022-08-08 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_daos_time_daos_createdat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daos',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='daos',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='daos',
            name='keyPermissions',
        ),
        migrations.RemoveField(
            model_name='daos',
            name='profileImage',
        ),
        migrations.RemoveField(
            model_name='daos',
            name='vaultDetails',
        ),
        migrations.RemoveField(
            model_name='daos',
            name='votingParameters',
        ),
    ]
