# Generated by Django 4.1 on 2022-08-08 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_daos_categories_remove_daos_createdat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daos',
            name='profileImage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.profileimagedicty'),
        ),
    ]
