# Generated by Django 4.1 on 2022-08-08 12:37

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_daos_createdat_alter_daos_profileimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoriesDicty',
        ),
        migrations.RemoveField(
            model_name='permissionsdicty',
            name='keyPermissions',
        ),
        migrations.DeleteModel(
            name='ProfileImageDicty',
        ),
        migrations.DeleteModel(
            name='VaultDicty',
        ),
        migrations.DeleteModel(
            name='VotingDicty',
        ),
        migrations.AddField(
            model_name='daos',
            name='categories',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='daos',
            name='keyPermissions',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='daos',
            name='vaultDetails',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='daos',
            name='votingParameters',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.DeleteModel(
            name='KeyPermissionsDicty',
        ),
        migrations.DeleteModel(
            name='PermissionsDicty',
        ),
    ]
