# Generated by Django 4.1 on 2022-08-12 06:55

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_delete_categoriesdicty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daos',
            name='URI',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='daos',
            name='creator',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='daos',
            name='daoUpAddress',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
