# Generated by Django 4.1 on 2022-08-12 09:45

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_daos_uri_daos_creator_daos_daoupaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daos',
            name='URI',
        ),
        migrations.AddField(
            model_name='daos',
            name='CID',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='daos',
            name='url',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
