# Generated by Django 4.1 on 2022-08-12 09:49

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_daos_uri_daos_cid_daos_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daos',
            name='createdAt',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
