# Generated by Django 4.1 on 2022-08-24 12:19

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_rename_fotdaodetails_proposal_fordaodetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('proposalContractAddress', jsonfield.fields.JSONField(null=True)),
                ('proposalName', models.CharField(max_length=50)),
                ('proposalUrl', jsonfield.fields.JSONField(null=True)),
                ('proposalSignature', jsonfield.fields.JSONField(null=True)),
                ('VoterSignature', jsonfield.fields.JSONField(null=True)),
                ('VoterChoice', jsonfield.fields.JSONField(null=True)),
                ('VoterAddress', jsonfield.fields.JSONField(null=True)),
                ('createdAt', jsonfield.fields.JSONField(null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
