# Generated by Django 4.1 on 2022-11-04 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_daos_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daos',
            old_name='link',
            new_name='daoLink',
        ),
    ]
